name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  rust-fmt:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Rustfmt
      run: rustfmt
    - uses: zwaldowski/git-commit-action@v1
      with:
        commit_message: Rustfmt cleaned up the Code!
  
  release-build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Release Build
      run: cargo build --release
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: U-RISC-Launcher
        path: target/release/u_risc_launcher
        if-no-files-found: error
      
    
