name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  rust-fmt:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Rustfmt
      run: rustfmt
    - uses: zwaldowski/git-commit-action@v1
      with:
        commit_message: Rustfmt cleaned up the Code!
  
  release-build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Release Build
      run: cargo build --release
    - name: Release Unstable
      uses: softprops/action-gh-release@v0.1.5
      with:
        body: THIS IS UNSTABLE DO NOT USE IT UNLESS YOU KNOW WHAT YOURE DOING!
        prerelease: true
        files: target/release/u_risc_launcher
      
    
